### ISSUE TITLE
Add-on not compatible?

### ISSUE THREAD

**Issue by brennanyoung** [nvdajp/focusHighlight#22]
When I try to install this add-on, NVDA tells me that it has been blocked - and that an updated version is required.
It says "the minimum add-on API supported by this version of NVDA is 2021.1"
Is there a new version of the add-on, and where can I find it?

**Comment by maxshuty** [comment]
I am also experiencing this issue. Is there any work around @nishimotz?

**Comment by maxshuty** [comment]
> Are you using the following? https://github.com/nvdajp/focusHighlight/releases/tag/6.4

@nishimotz - I was referencing 6.3 because [the addons page](https://addons.nvda-project.org/addons/focusHighlight.en.html) lists that version as the latest one. However, 6.4 does work just fine. Thank you, and thanks for the hard work on accessibility issues!

**Comment by brennanyoung** [comment]
Yep, thanks! It's the addons page that needs updating, so I suppose it's 'their' issue. (Also I think the focusHighlight behavior is available by default in NVDA now, no?) 

So.. nothing to 'fix' in focusHighlight, although I'm hesitant to close this issue until the addons page is updated, because others will encounter the same problem, and assume that focusHighlight has fallen behind. This thread will be helpful for those people.

**Comment by CyrilleB79** [comment]
@nishimotz, as an add-on author, could you please make the following updates for the add-on distribution on the community website:
* PR against [addonFiles](https://github.com/nvaccess/addonFiles) repo to have the download link updated in get.php to point to version 6.4
* Update the website documentation of this add-on in screenreadertranslations SVN repo
If you are not able to do this or face any issue, please send a message to nvda-addons mailing list to ask for assistance.

**Comment by nishimotz** [comment]
Thank you for your advice.
I did the following:
https://github.com/nvaccess/addonFiles/pull/258

**Comment by nishimotz** [comment]
version 6.5 is out.
https://github.com/nvdajp/focusHighlight/releases/tag/6.5

I will make PR against addonFiles repository again.
